### ISSUE TITLE
Bug in the last exercise of chapter 2.7

### ISSUE THREAD

**Issue by Xiaojin-Nan** [jijingg/Spinal-bootcamp#4]
# Description
I copy this code to my intellij:

```
class MySub extends Component {
    val io = new Bundle{
        val a = in UInt(8 bits)
        val b = out UInt(8 bits)
    }
    io.b := RegNext(io.a) init(0)
}
class Top extends Component {
    val io = new Bundle{
        val a0,a1 = in UInt(8 bits)
        val cg_en0,cg_en1 = in Bool
        val b  = out UInt(8 bits)
    }
    val gated_clk0: Bool = CG(clockDomain, io.cg_en0, False)
    val gated_clk1: Bool = CG(clockDomain, io.cg_en1, False)
    
    val cgd0 = ClockDomain(gated_clk0, clockDomain.readResetWire)
    val cgd1 = ClockDomain(gated_clk1, clockDomain.readResetWire)
    cgd0.setSyncWith(cgd1)   // set Two clock Family as synchronous , valid on SpinalHDL1.3.7
    val u_sub0 = cgd0(new MySub)
    val u_sub1 = cgd1(new MySub)
    
    u_sub0.io.a := io.a0
    u_sub1.io.a := io.a1
    io.b := RegNext(u_sub0.io.b + u_sub1.io.b) init 0
}
```
In this code,the synchronous information is indicated
```
    cgd0.setSyncWith(cgd1)   // set Two clock Family as synchronous , valid on SpinalHDL1.3.7
```
But there are still errors about cross domain.Why?

> CLOCK CROSSING VIOLATION :
> - Source            : (toplevel/u_sub0/io_a_regNext :  UInt[8 bits]) java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> - Source clock      : (toplevel/[CG]/ECK : out Bool)
> - Destination       : (toplevel/??? :  UInt[8 bits]) java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> - Destination clock : (clk :  Bool)
> - Source declaration :

# Environment:
OS:WIN10
Intellij IDEA:2019.3.3
JDK:1.8
Scala:2.11.12
SpinalHDL:1.4.1

**Comment by jijingg** [comment]
@AlkaidDoge sorry, my fault, the old example is out of date. The new implementation has been updated in e754d5e

**Comment by Xiaojin-Nan** [comment]
@jijingg Thank you very much for your timely repair, but I had a little problem running the new implementation.
I copy your code into Intellij IDEA, then it tell me "protected" modifier is no allowed here.But I can run code in jupyter,why?
(Although I take out "protected" and it works....)
```
protected object CommonCellBlackBox {
    private var _clear: Boolean = false
    def clear: Boolean = _clear
    def clear_=(x: Boolean) { _clear = x}
  }
```

**Comment by jijingg** [comment]
@AlkaidDoge `protected` is not necessary  here , but in the lib `CommonCellBlackBox` is not need open for Users， so i limit it's scope.
It depends on your design.

```
package object commonCell {
.....
  protected[commonCell] object CommonCellBlackBox {
    private var _clear: Boolean = false
    def clear: Boolean = _clear
    def clear_=(x: Boolean) { _clear = x}
  }

  object clearCCBB{
    def apply() = CommonCellBlackBox.clear = true
  }
}
```

**Comment by Xiaojin-Nan** [comment]
Okay.Thank you for your answer. I don't have any questions. : )
