### ISSUE TITLE
SpinalHDL libraries will not load

### ISSUE THREAD

**Issue by domenicw** [jijingg/Spinal-bootcamp#8]
I am unable to load the SpinalHDL libraries, both on macOS and on Linux. All the tools are installed and the Scala kernel is running. 

```
Downloading https://repo1.maven.org/maven2/com/github/spinalhdl/spinalhdl-core_2.13/1.4.1/spinalhdl-core_2.13-1.4.1.pom
Downloaded https://repo1.maven.org/maven2/com/github/spinalhdl/spinalhdl-core_2.13/1.4.1/spinalhdl-core_2.13-1.4.1.pom
Downloading https://repo1.maven.org/maven2/com/github/spinalhdl/spinalhdl-core_2.13/1.4.1/spinalhdl-core_2.13-1.4.1.pom.sha1
Downloaded https://repo1.maven.org/maven2/com/github/spinalhdl/spinalhdl-core_2.13/1.4.1/spinalhdl-core_2.13-1.4.1.pom.sha1
ammonite.util.CompilationError: Failed to resolve ivy dependencies:Error downloading com.github.spinalhdl:spinalhdl-core_2.13:1.4.1
  not found: /Users/domenic/.ivy2/local/com.github.spinalhdl/spinalhdl-core_2.13/1.4.1/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/com/github/spinalhdl/spinalhdl-core_2.13/1.4.1/spinalhdl-core_2.13-1.4.1.pom
  ammonite.interp.Interpreter$$anon$1$load$.module(Interpreter.scala:693)
  ammonite.$sess.cmd0$Helper.<init>(cmd0.sc:2)
  ammonite.$sess.cmd0$.<clinit>(cmd0.sc:7)
```

The issue is probably with the version number. spinalhdl-core_2.13 does not exit at https://repo1.maven.org. Only version 2.11 and 2.12 do exist. How can I change the version number. I did not find anything in the load-spinal.sc file to change that.

**Comment by jijingg** [comment]
hi @domenicw , you need install Scala2.12 instead Scala2.13 on your PC. Scala2.13 incompatible with pre-version, and the latest Spinal still based on Scala2.12

**Comment by domenicw** [comment]
Thank you for your answer, I actually got it working. I had the correct version of Scala installed (2.12) but the issue was with almond.

```bash
./coursier launch --fork almond:0.5.0 --scala 2.12.6 -- --install
```

Specifying the Scala version there during installation fixed it for me.
Thanks
