### ISSUE TITLE
fail to download Spinalhdl

### ISSUE THREAD

**Issue by syibin** [jijingg/Spinal-bootcamp#9]
Hi, 
When I try to execute following code:
val path = System.getProperty("user.dir") + "/source/load-spinal.sc"
interp.load.module(ammonite.ops.Path(java.nio.file.FileSystems.getDefault().getPath(path)))

I will encounter following error:
ammonite.util.CompilationError: Failed to resolve ivy dependencies:Error downloading com.github.spinalhdl:spinalhdl-core_2.13:1.4.1
  not found: /Users//.ivy2/local/com.github.spinalhdl/spinalhdl-core_2.13/1.4.1/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/com/github/spinalhdl/spinalhdl-core_2.13/1.4.1/spinalhdl-core_2.13-1.4.1.pom

According to https://repo1.maven.org/maven2/com/github/spinalhdl/, there is no 2.13 version available.

I try to replace all 2.13 to 2.12 in 1.1-Spinal-quick-start.ipynb file and then rerun, however, it doesn't work - still same error messages.

I'd like to ask how to fix this issue. Thanks in advance for the help!

**Comment by jijingg** [comment]
@syibin open Jupyte Notebook, then click **help** -> **about** -> ,  make sure the current service infomathion is :
```
....
Scala library version 2.12.x 
Java 1.8.x
```
if not ,try uninstall 2.13 version , make sure the scala2.12 add to the PATH

**Comment by syibin** [comment]
Hi, @jijingg 

Thanks for your timely help! As you said, I was using scala2.13.

The root cause is I just used the default following command as suggested (https://almond.sh/docs/quick-start-install) :
 ./coursier launch --fork almond -- --install
with this command, the default scala version for now is 2.13.

After I remove the original kernel and reinstall with following command, now everything works as expected. :)
./coursier launch --fork almond:0.10.0 --scala 2.12.11 -- --install
